### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by CasperLaiTW** [codebar-ag/Laravel-Prerender#6]
Add few test cases for middleware.

**Comment by StanBarrows** [comment]
Good Morning @CasperLaiTW 

Do you know how to set a Matrix correctly? Currently it is testing all PHP Versions against all Laravel Versions etc.

Let's say:

- if you use PHP 7.2 use Laravel 6 and Testbench 4.*

- if you use PHP 7.2 use Laravel 7 and Testbench 5.*
- if you use PHP 7.3 use Laravel 7 and Testbench 5.*

- if you use PHP 7.3 use Laravel 8 and Testbench 6.*
- if you use PHP 7.4 use Laravel 8 and Testbench 6.*

**ATM i've the following setup.**

```
name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.2,7.3,7.4]
        laravel: [6.*,7.*,8.*]
        testbench: [4.*,5.*,6.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 6.*
            testbench: 4.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Execute tests
        run: vendor/bin/phpunit

```
